In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df = sns.load_dataset('iris')

In [3]:
df.head()

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [4]:
df['species'].unique()

array(['setosa', 'versicolor', 'virginica'], dtype=object)

In [5]:
from sklearn.model_selection import train_test_split

In [6]:
X = df.drop('species',axis = 1)
Y = df['species']

In [7]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, random_state=42)

In [8]:
from sklearn.neighbors import KNeighborsClassifier

In [9]:
model_knn = KNeighborsClassifier(n_neighbors = 5)

In [10]:
model_knn.fit(X_train,Y_train)

KNeighborsClassifier()

In [11]:
model_knn.score(X_test,Y_test)

1.0

# Clearly Overffitting

In [12]:
from sklearn.svm import SVC

In [14]:
model_svm = SVC(C = 30,kernel = 'rbf' , gamma = 'auto')

In [15]:
model_svm.fit(X_train,Y_train)

SVC(C=30, gamma='auto')

In [16]:
model_svm.score(X_test,Y_test)

1.0

# AGAIN Clearly Overfitting

# NOW LET'S USE GRID-SEARCH-CV

In [18]:
from sklearn.model_selection import GridSearchCV

In [19]:
svm_model = SVC(gamma = 'auto')

In [21]:
classifier = GridSearchCV((svm_model),{
    'C' : [1,10,20,30,40],
    'kernel' : ['rbf','linear']
},cv = 5 , return_train_score =False)

In [22]:
classifier.fit(X,Y)

GridSearchCV(cv=5, estimator=SVC(gamma='auto'),
             param_grid={'C': [1, 10, 20, 30, 40], 'kernel': ['rbf', 'linear']})

In [24]:
results = pd.DataFrame(classifier.cv_results_)

In [25]:
results

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_C,param_kernel,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.001563,0.000316,0.001053,0.000218,1,rbf,"{'C': 1, 'kernel': 'rbf'}",0.966667,1.000000,0.966667,0.966667,1.0,0.980000,0.016330,1
1,0.000967,0.000070,0.000681,0.000040,1,linear,"{'C': 1, 'kernel': 'linear'}",0.966667,1.000000,0.966667,0.966667,1.0,0.980000,0.016330,1
2,0.001218,0.000301,0.000994,0.000346,10,rbf,"{'C': 10, 'kernel': 'rbf'}",0.966667,1.000000,0.966667,0.966667,1.0,0.980000,0.016330,1
3,0.001147,0.000380,0.000716,0.000258,10,linear,"{'C': 10, 'kernel': 'linear'}",1.000000,1.000000,0.900000,0.966667,1.0,0.973333,0.038873,4
4,0.000550,0.000015,0.000384,0.000008,20,rbf,"{'C': 20, 'kernel': 'rbf'}",0.966667,1.000000,0.900000,0.966667,1.0,0.966667,0.036515,5
5,0.000658,0.000243,0.000449,0.000087,20,linear,"{'C': 20, 'kernel': 'linear'}",1.000000,1.000000,0.900000,0.933333,1.0,0.966667,0.042164,6
6,0.000556,0.000096,0.000377,0.000051,30,rbf,"{'C': 30, 'kernel': 'rbf'}",0.966667,1.000000,0.900000,0.933333,1.0,0.960000,0.038873,7
7,0.000450,0.000013,0.000318,0.000002,30,linear,"{'C': 30, 'kernel': 'linear'}",1.000000,1.000000,0.900000,0.900000,1.0,0.960000,0.048990,7
8,0.000532,0.000066,0.000368,0.000053,40,rbf,"{'C': 40, 'kernel': 'rbf'}",1.000000,0.966667,0.900000,0.933333,1.0,0.960000,0.038873,7
9,0.000441,0.000007,0.000314,0.000009,40,linear,"{'C': 40, 'kernel': 'linear'}",1.000000,1.000000,0.900000,0.900000,1.0,0.960000,0.048990,7

In [28]:
results[['param_C','param_kernel','mean_test_score']]

   param_C param_kernel  mean_test_score
0        1          rbf         0.980000
1        1       linear         0.980000
2       10          rbf         0.980000
3       10       linear         0.973333
4       20          rbf         0.966667
5       20       linear         0.966667
6       30          rbf         0.960000
7       30       linear         0.960000
8       40          rbf         0.960000
9       40       linear         0.960000

In [29]:
knn_model = KNeighborsClassifier()

In [35]:
classifier_knn = GridSearchCV((knn_model),{
    'n_neighbors' : [1,3,5,7,9,11,13,15,17,19,21,23,25,27,28,31],
    'weights' : ['uniform' , 'distance'],
    'algorithm' : ['auto', 'ball_tree', 'kd_tree', 'brute']
},cv = 5 , return_train_score =False)

In [36]:
classifier_knn.fit(X,Y)

GridSearchCV(cv=5, estimator=KNeighborsClassifier(),
             param_grid={'algorithm': ['auto', 'ball_tree', 'kd_tree', 'brute'],
                         'n_neighbors': [1, 3, 5, 7, 9, 11, 13, 15, 17, 19, 21,
                                         23, 25, 27, 28, 31],
                         'weights': ['uniform', 'distance']})

In [37]:
results = pd.DataFrame(classifier_knn.cv_results_)

In [38]:
results

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_algorithm,param_n_neighbors,param_weights,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.001341,0.000356,0.002011,0.000823,auto,1,uniform,"{'algorithm': 'auto', 'n_neighbors': 1, 'weigh...",0.966667,0.966667,0.933333,0.933333,1.0,0.960000,0.024944,101
1,0.000946,0.000125,0.001139,0.000207,auto,1,distance,"{'algorithm': 'auto', 'n_neighbors': 1, 'weigh...",0.966667,0.966667,0.933333,0.933333,1.0,0.960000,0.024944,101
2,0.000679,0.000112,0.000996,0.000185,auto,3,uniform,"{'algorithm': 'auto', 'n_neighbors': 3, 'weigh...",0.966667,0.966667,0.933333,0.966667,1.0,0.966667,0.021082,65
3,0.000616,0.000075,0.000727,0.000095,auto,3,distance,"{'algorithm': 'auto', 'n_neighbors': 3, 'weigh...",0.966667,0.966667,0.933333,0.966667,1.0,0.966667,0.021082,65
4,0.000521,0.000034,0.000910,0.000197,auto,5,uniform,"{'algorithm': 'auto', 'n_neighbors': 5, 'weigh...",0.966667,1.000000,0.933333,0.966667,1.0,0.973333,0.024944,26
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
123,0.000303,0.000002,0.000762,0.000021,brute,27,distance,"{'algorithm': 'brute', 'n_neighbors': 27, 'wei...",0.966667,0.966667,0.966667,0.966667,1.0,0.973333,0.013333,26
124,0.000301,0.000006,0.000770,0.000018,brute,28,uniform,"{'algorithm': 'brute', 'n_neighbors': 28, 'wei...",0.900000,0.966667,0.933333,0.900000,1.0,0.940000,0.038873,121
125,0.000304,0.000002,0.000791,0.000021,brute,28,distance,"{'algorithm': 'brute', 'n_neighbors': 28, 'wei...",0.966667,0.966667,0.900000,0.966667,1.0,0.960000,0.032660,97
126,0.000304,0.000003,0.000758,0.000009,brute,31,uniform,"{'algorithm': 'brute', 'n_neighbors': 31, 'wei...",0.900000,0.966667,0.900000,0.900000,1.0,0.933333,0.042164,125
127,0.000301,0.000003,0.000763,0.000019,brute,31,distance,"{'algorithm': 'brute', 'n_neighbors': 31, 'wei...",0.966667,0.966667,0.966667,0.966667,1.0,0.973333,0.013333,26

In [39]:
results[['param_algorithm','param_n_neighbors','param_weights','mean_test_score']]

    param_algorithm  param_n_neighbors param_weights  mean_test_score
0              auto                  1       uniform         0.960000
1              auto                  1      distance         0.960000
2              auto                  3       uniform         0.966667
3              auto                  3      distance         0.966667
4              auto                  5       uniform         0.973333
..              ...                ...           ...              ...
123           brute                 27      distance         0.973333
124           brute                 28       uniform         0.940000
125           brute                 28      distance         0.960000
126           brute                 31       uniform         0.933333
127           brute                 31      distance         0.973333

[128 rows x 4 columns]

In [40]:
classifier_knn.best_params_

{'algorithm': 'auto', 'n_neighbors': 11, 'weights': 'distance'}

In [41]:
classifier_knn.best_score_

np.float64(0.9866666666666667)