In [35]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [36]:
df = sns.load_dataset('iris')

In [37]:
df.head()

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [38]:
df['species'].unique()

array(['setosa', 'versicolor', 'virginica'], dtype=object)

In [39]:
from sklearn.model_selection import train_test_split

In [40]:
X = df.drop('species',axis = 1)
Y = df['species']

In [41]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, random_state=42)

In [42]:
from sklearn.neighbors import KNeighborsClassifier

In [43]:
model_knn = KNeighborsClassifier(n_neighbors = 5)

In [44]:
model_knn.fit(X_train,Y_train)

KNeighborsClassifier()

In [45]:
model_knn.score(X_test,Y_test)

1.0

# Clearly Overffitting

In [46]:
from sklearn.svm import SVC

In [47]:
model_svm = SVC(C = 30,kernel = 'rbf' , gamma = 'auto')

In [48]:
model_svm.fit(X_train,Y_train)

SVC(C=30, gamma='auto')

In [49]:
model_svm.score(X_test,Y_test)

1.0

# AGAIN Clearly Overfitting

# NOW LET'S USE GRID-SEARCH-CV

In [50]:
from sklearn.model_selection import GridSearchCV

In [51]:
svm_model = SVC(gamma = 'auto')

In [52]:
classifier = GridSearchCV((svm_model),{
    'C' : [1,10,20,30,40],
    'kernel' : ['rbf','linear']
},cv = 5 , return_train_score =False)

In [53]:
classifier.fit(X,Y)

GridSearchCV(cv=5, estimator=SVC(gamma='auto'),
             param_grid={'C': [1, 10, 20, 30, 40], 'kernel': ['rbf', 'linear']})

In [54]:
results = pd.DataFrame(classifier.cv_results_)

In [55]:
results

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_C,param_kernel,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.000648,0.000122,0.000483,0.000118,1,rbf,"{'C': 1, 'kernel': 'rbf'}",0.966667,1.000000,0.966667,0.966667,1.0,0.980000,0.016330,1
1,0.000451,0.000015,0.000322,0.000010,1,linear,"{'C': 1, 'kernel': 'linear'}",0.966667,1.000000,0.966667,0.966667,1.0,0.980000,0.016330,1
2,0.000555,0.000066,0.000444,0.000129,10,rbf,"{'C': 10, 'kernel': 'rbf'}",0.966667,1.000000,0.966667,0.966667,1.0,0.980000,0.016330,1
3,0.000577,0.000077,0.000394,0.000046,10,linear,"{'C': 10, 'kernel': 'linear'}",1.000000,1.000000,0.900000,0.966667,1.0,0.973333,0.038873,4
4,0.000527,0.000082,0.000360,0.000037,20,rbf,"{'C': 20, 'kernel': 'rbf'}",0.966667,1.000000,0.900000,0.966667,1.0,0.966667,0.036515,5
5,0.000555,0.000075,0.000380,0.000068,20,linear,"{'C': 20, 'kernel': 'linear'}",1.000000,1.000000,0.900000,0.933333,1.0,0.966667,0.042164,6
6,0.000497,0.000061,0.000361,0.000047,30,rbf,"{'C': 30, 'kernel': 'rbf'}",0.966667,1.000000,0.900000,0.933333,1.0,0.960000,0.038873,7
7,0.000466,0.000042,0.000316,0.000029,30,linear,"{'C': 30, 'kernel': 'linear'}",1.000000,1.000000,0.900000,0.900000,1.0,0.960000,0.048990,7
8,0.000501,0.000059,0.000348,0.000040,40,rbf,"{'C': 40, 'kernel': 'rbf'}",1.000000,0.966667,0.900000,0.933333,1.0,0.960000,0.038873,7
9,0.000452,0.000023,0.000317,0.000017,40,linear,"{'C': 40, 'kernel': 'linear'}",1.000000,1.000000,0.900000,0.900000,1.0,0.960000,0.048990,7

In [56]:
results[['param_C','param_kernel','mean_test_score']]

   param_C param_kernel  mean_test_score
0        1          rbf         0.980000
1        1       linear         0.980000
2       10          rbf         0.980000
3       10       linear         0.973333
4       20          rbf         0.966667
5       20       linear         0.966667
6       30          rbf         0.960000
7       30       linear         0.960000
8       40          rbf         0.960000
9       40       linear         0.960000

In [57]:
knn_model = KNeighborsClassifier()

In [58]:
classifier_knn = GridSearchCV((knn_model),{
    'n_neighbors' : [1,3,5,7,9,11,13,15,17,19,21,23,25,27,28,31],
    'weights' : ['uniform' , 'distance'],
    'algorithm' : ['auto', 'ball_tree', 'kd_tree', 'brute']
},cv = 5 , return_train_score =False)

In [59]:
classifier_knn.fit(X,Y)

GridSearchCV(cv=5, estimator=KNeighborsClassifier(),
             param_grid={'algorithm': ['auto', 'ball_tree', 'kd_tree', 'brute'],
                         'n_neighbors': [1, 3, 5, 7, 9, 11, 13, 15, 17, 19, 21,
                                         23, 25, 27, 28, 31],
                         'weights': ['uniform', 'distance']})

In [60]:
results = pd.DataFrame(classifier_knn.cv_results_)

In [61]:
results

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_algorithm,param_n_neighbors,param_weights,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.000519,0.000116,0.000747,0.000112,auto,1,uniform,"{'algorithm': 'auto', 'n_neighbors': 1, 'weigh...",0.966667,0.966667,0.933333,0.933333,1.0,0.960000,0.024944,101
1,0.000364,0.000008,0.000418,0.000021,auto,1,distance,"{'algorithm': 'auto', 'n_neighbors': 1, 'weigh...",0.966667,0.966667,0.933333,0.933333,1.0,0.960000,0.024944,101
2,0.000375,0.000036,0.000579,0.000067,auto,3,uniform,"{'algorithm': 'auto', 'n_neighbors': 3, 'weigh...",0.966667,0.966667,0.933333,0.966667,1.0,0.966667,0.021082,65
3,0.000329,0.000007,0.000394,0.000019,auto,3,distance,"{'algorithm': 'auto', 'n_neighbors': 3, 'weigh...",0.966667,0.966667,0.933333,0.966667,1.0,0.966667,0.021082,65
4,0.000410,0.000078,0.000591,0.000079,auto,5,uniform,"{'algorithm': 'auto', 'n_neighbors': 5, 'weigh...",0.966667,1.000000,0.933333,0.966667,1.0,0.973333,0.024944,26
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
123,0.000297,0.000005,0.000766,0.000031,brute,27,distance,"{'algorithm': 'brute', 'n_neighbors': 27, 'wei...",0.966667,0.966667,0.966667,0.966667,1.0,0.973333,0.013333,26
124,0.000299,0.000007,0.000748,0.000034,brute,28,uniform,"{'algorithm': 'brute', 'n_neighbors': 28, 'wei...",0.900000,0.966667,0.933333,0.900000,1.0,0.940000,0.038873,121
125,0.000296,0.000002,0.000729,0.000025,brute,28,distance,"{'algorithm': 'brute', 'n_neighbors': 28, 'wei...",0.966667,0.966667,0.900000,0.966667,1.0,0.960000,0.032660,97
126,0.000298,0.000007,0.000762,0.000023,brute,31,uniform,"{'algorithm': 'brute', 'n_neighbors': 31, 'wei...",0.900000,0.966667,0.900000,0.900000,1.0,0.933333,0.042164,125
127,0.000301,0.000004,0.000757,0.000016,brute,31,distance,"{'algorithm': 'brute', 'n_neighbors': 31, 'wei...",0.966667,0.966667,0.966667,0.966667,1.0,0.973333,0.013333,26

In [62]:
results[['param_algorithm','param_n_neighbors','param_weights','mean_test_score']]

    param_algorithm  param_n_neighbors param_weights  mean_test_score
0              auto                  1       uniform         0.960000
1              auto                  1      distance         0.960000
2              auto                  3       uniform         0.966667
3              auto                  3      distance         0.966667
4              auto                  5       uniform         0.973333
..              ...                ...           ...              ...
123           brute                 27      distance         0.973333
124           brute                 28       uniform         0.940000
125           brute                 28      distance         0.960000
126           brute                 31       uniform         0.933333
127           brute                 31      distance         0.973333

[128 rows x 4 columns]

In [63]:
classifier_knn.best_params_

{'algorithm': 'auto', 'n_neighbors': 11, 'weights': 'distance'}

In [64]:
classifier_knn.best_score_

np.float64(0.9866666666666667)

In [65]:
from sklearn.model_selection import RandomizedSearchCV

In [66]:
classifier_knn_r = RandomizedSearchCV((knn_model),{
    'n_neighbors' : [1,3,5,7,9,11,13,15,17,19,21,23,25,27,28,31],
    'weights' : ['uniform' , 'distance'],
    'algorithm' : ['auto', 'ball_tree', 'kd_tree', 'brute']
},n_iter = 20,cv = 5 , return_train_score =False)

In [68]:
classifier_knn_r.fit(X,Y)

RandomizedSearchCV(cv=5, estimator=KNeighborsClassifier(), n_iter=20,
                   param_distributions={'algorithm': ['auto', 'ball_tree',
                                                      'kd_tree', 'brute'],
                                        'n_neighbors': [1, 3, 5, 7, 9, 11, 13,
                                                        15, 17, 19, 21, 23, 25,
                                                        27, 28, 31],
                                        'weights': ['uniform', 'distance']})

In [69]:
results = pd.DataFrame(classifier_knn_r.cv_results_)

In [70]:
results

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_weights,param_n_neighbors,param_algorithm,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.001261,0.000381,0.001860,0.000651,distance,21,brute,"{'weights': 'distance', 'n_neighbors': 21, 'al...",0.966667,1.000000,0.933333,0.966667,1.0,0.973333,0.024944,5
1,0.000873,0.000178,0.001092,0.000206,distance,7,ball_tree,"{'weights': 'distance', 'n_neighbors': 7, 'alg...",0.966667,1.000000,0.966667,0.966667,1.0,0.980000,0.016330,1
2,0.000543,0.000053,0.000714,0.000073,distance,27,kd_tree,"{'weights': 'distance', 'n_neighbors': 27, 'al...",0.966667,0.966667,0.966667,0.966667,1.0,0.973333,0.013333,5
3,0.000577,0.000099,0.000851,0.000163,uniform,9,kd_tree,"{'weights': 'uniform', 'n_neighbors': 9, 'algo...",0.966667,1.000000,0.966667,0.933333,1.0,0.973333,0.024944,5
4,0.000564,0.000054,0.000885,0.000089,uniform,11,auto,"{'weights': 'uniform', 'n_neighbors': 11, 'alg...",0.933333,1.000000,1.000000,0.966667,1.0,0.980000,0.026667,1
5,0.000518,0.000034,0.000641,0.000050,distance,23,ball_tree,"{'weights': 'distance', 'n_neighbors': 23, 'al...",0.966667,1.000000,0.966667,0.966667,1.0,0.980000,0.016330,1
6,0.000544,0.000075,0.000643,0.000057,distance,25,auto,"{'weights': 'distance', 'n_neighbors': 25, 'al...",0.966667,0.966667,0.933333,0.966667,1.0,0.966667,0.021082,11
7,0.000435,0.000030,0.000919,0.000063,distance,1,brute,"{'weights': 'distance', 'n_neighbors': 1, 'alg...",0.966667,0.966667,0.933333,0.933333,1.0,0.960000,0.024944,16
8,0.000418,0.000018,0.000673,0.000058,uniform,27,kd_tree,"{'weights': 'uniform', 'n_neighbors': 27, 'alg...",0.900000,0.966667,0.933333,0.933333,1.0,0.946667,0.033993,19
9,0.000376,0.000009,0.000454,0.000016,distance,17,ball_tree,"{'weights': 'distance', 'n_neighbors': 17, 'al...",0.966667,1.000000,0.933333,0.966667,1.0,0.973333,0.024944,5
10,0.000347,0.000007,0.000558,0.000014,uniform,28,ball_tree,"{'weights': 'uniform', 'n_neighbors': 28, 'alg...",0.900000,0.966667,0.933333,0.900000,1.0,0.940000,0.038873,20
11,0.000346,0.000010,0.000433,0.000005,distance,31,kd_tree,"{'weights': 'distance', 'n_neighbors': 31, 'al...",0.966667,0.966667,0.966667,0.966667,1.0,0.973333,0.013333,5
12,0.000313,0.000006,0.000800,0.000046,uniform,7,brute,"{'weights': 'uniform', 'n_neighbors': 7, 'algo...",0.966667,1.000000,0.966667,0.966667,1.0,0.980000,0.016330,1
13,0.000296,0.000005,0.000798,0.000047,distance,28,brute,"{'weights': 'distance', 'n_neighbors': 28, 'al...",0.966667,0.966667,0.900000,0.966667,1.0,0.960000,0.032660,15
14,0.000314,0.000004,0.000356,0.000004,distance,1,auto,"{'weights': 'distance', 'n_neighbors': 1, 'alg...",0.966667,0.966667,0.933333,0.933333,1.0,0.960000,0.024944,16
15,0.000313,0.000004,0.000439,0.000090,distance,25,ball_tree,"{'weights': 'distance', 'n_neighbors': 25, 'al...",0.966667,0.966667,0.933333,0.966667,1.0,0.966667,0.021082,11
16,0.000320,0.000020,0.000495,0.000015,uniform,19,kd_tree,"{'weights': 'uniform', 'n_neighbors': 19, 'alg...",0.933333,1.000000,0.933333,0.966667,1.0,0.966667,0.029814,11
17,0.000311,0.000011,0.000853,0.000058,uniform,25,brute,"{'weights': 'uniform', 'n_neighbors': 25, 'alg...",0.933333,0.966667,0.933333,0.966667,1.0,0.960000,0.024944,16
18,0.000322,0.000009,0.000381,0.000017,distance,3,auto,"{'weights': 'distance', 'n_neighbors': 3, 'alg...",0.966667,0.966667,0.933333,0.966667,1.0,0.966667,0.021082,11
19,0.000315,0.000003,0.000388,0.000008,distance,19,auto,"{'weights': 'distance', 'n_neighbors': 19, 'al...",0.966667,1.000000,0.933333,0.966667,1.0,0.973333,0.024944,5

In [71]:
results[['param_weights','param_n_neighbors','param_algorithm','mean_test_score']]

   param_weights  param_n_neighbors param_algorithm  mean_test_score
0       distance                 21           brute         0.973333
1       distance                  7       ball_tree         0.980000
2       distance                 27         kd_tree         0.973333
3        uniform                  9         kd_tree         0.973333
4        uniform                 11            auto         0.980000
5       distance                 23       ball_tree         0.980000
6       distance                 25            auto         0.966667
7       distance                  1           brute         0.960000
8        uniform                 27         kd_tree         0.946667
9       distance                 17       ball_tree         0.973333
10       uniform                 28       ball_tree         0.940000
11      distance                 31         kd_tree         0.973333
12       uniform                  7           brute         0.980000
13      distance                 28           brute         0.960000
14      distance                  1            auto         0.960000
15      distance                 25       ball_tree         0.966667
16       uniform                 19         kd_tree         0.966667
17       uniform                 25           brute         0.960000
18      distance                  3            auto         0.966667
19      distance                 19            auto         0.973333

In [72]:
classifier_knn_r.best_score_

np.float64(0.9800000000000001)

In [74]:
classifier_knn_r.best_params_

{'weights': 'distance', 'n_neighbors': 7, 'algorithm': 'ball_tree'}